### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Free-ToT** [xiuqhou/Salience-DETR#24]
### Bug

配置好环境后报错ModuleNotFoundError: No module named 'fvcore.common'
misc.py文件报错在'init_.py'中找不到引用'common':16未解析的引用'PathManager' :16未解析的引用'pygments' :113未解析的引用'Terminal256Formatter' :113未解析的引用'pygments':114未解析的引用'Python3Lexer':114未解析的引用'YamlLexer' :114

### 环境信息

环境按照官方引导配置在RTX4060 Windows系统上

**Comment by xiuqhou** [comment]
有原始输出的报错信息吗？可能是fvcore版本不对，用下面命令升级版本试试：

```shell
pip install -U 'git+https://github.com/facebookresearch/fvcore'
```

**Comment by Free-ToT** [comment]
Traceback (most recent call last):
  File "E:\Salience-DETR\main.py", line 16, in <module>
    from util.collate_fn import collate_fn
  File "E:\Salience-DETR\util\collate_fn.py", line 5, in <module>
    from util.misc import to_device
  File "E:\Salience-DETR\util\misc.py", line 16, in <module>
    from fvcore.common.file_io import PathManager
ModuleNotFoundError: No module named 'fvcore.common'

**Comment by xiuqhou** [comment]
升级fvcore版本后问题还存在吗？我是用的fvcore版本是`0.1.5.post20221221`版本，如果还不行可以试试我用的版本：

```
pip install fvcore==0.1.5.post20221221
```

**Comment by Free-ToT** [comment]
还是不行，用你的版本也不行，我下来再找找原因吧 谢谢

**Comment by Free-ToT** [comment]
还是原来的问题，util.misc.py中import部分报错
Traceback (most recent call last):
  File "E:\Salience-DETR\main.py", line 16, in <module>
    from util.collate_fn import collate_fn
  File "E:\Salience-DETR\util\collate_fn.py", line 5, in <module>
    from util.misc import to_device
  File "E:\Salience-DETR\util\misc.py", line 16, in <module>
    from fvcore.common.file_io import PathManager
ModuleNotFoundError: No module named 'fvcore.common'

**Comment by xiuqhou** [comment]
代码中有两处用到了fvcore.common，现在我都改过来了，请用最新版仓库代码试一试。
