### ISSUE TITLE
训练的时候出现问题：RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by oneofforgettable** [xiuqhou/Salience-DETR#30]
### Question

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 8, 1092, 1092]], which is output 0 of ReluBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### 补充信息

Traceback (most recent call last):
  File "main.py", line 222, in <module>
    train()
  File "main.py", line 195, in train
    train_one_epoch_acc(
  File "/home/xx/DETR/Relation-DETR/util/engine.py", line 58, in train_one_epoch_acc
    accelerator.backward(losses)
  File "/home/xx/.conda/envs/rdetr/lib/python3.8/site-packages/accelerate/accelerator.py", line 2151, in backward
    loss.backward(**kwargs)
  File "/home/xx/.conda/envs/rdetr/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/xx/.conda/envs/rdetr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

**Comment by xiuqhou** [comment]
Hi，这个问题应该是[Relation-DETR](https://github.com/xiuqhou/Relation-DETR)的bug，今天下午有其他研究者提出了相同的问题，链接在[这里](https://github.com/xiuqhou/Relation-DETR/issues/5)，我们下午修复了这个bug。您手头的代码可能不是最新版，请用最新版再试试看呢！

因为这不是本仓库[Salience-DETR](https://github.com/xiuqhou/Salience-DETR)的问题，所以我先把issue关掉了哈，如果有问题可以在Relation-DETR的仓库开个issue~
