### ISSUE TITLE
[Bug]: ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by autoencoder-zz** [xiuqhou/Salience-DETR#39]
### Bug

在训练程序的时候（使用两块显卡），报错以下信息：
Traceback (most recent call last):
  File "main.py", line 203, in <module>
    train()
  File "main.py", line 176, in train
Traceback (most recent call last):
  File "main.py", line 203, in <module>
    train_one_epoch_acc(
  File "/home/ubuntu/ztt/python project/salience_detr/util/engine.py", line 46, in train_one_epoch_acc
    loss_dict = model(images, targets)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    train()
  File "main.py", line 176, in train
    train_one_epoch_acc(
  File "/home/ubuntu/ztt/python project/salience_detr/util/engine.py", line 46, in train_one_epoch_acc
    return self._call_impl(*args, **kwargs)
      File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
loss_dict = model(images, targets)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)    
else self._run_ddp_forward(*inputs, **kwargs)  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward

  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self._call_impl(*args, **kwargs)    
return self.module(*inputs, **kwargs)  # type: ignore[index]  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      return forward_call(*args, **kwargs)    
return self._call_impl(*args, **kwargs)  File "/home/ubuntu/ztt/python project/salience_detr/models/detectors/salience_detr.py", line 271, in forward
 File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
loss_dict = model(images, targets)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)    
else self._run_ddp_forward(*inputs, **kwargs)  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward

  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self._call_impl(*args, **kwargs)    
return self.module(*inputs, **kwargs)  # type: ignore[index]  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl

  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)    
return self._call_impl(*args, **kwargs)  File "/home/ubuntu/ztt/python project/salience_detr/models/detectors/salience_detr.py", line 271, in forward
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    loss_dict = self.criterion(output, targets)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
File "/home/ubuntu/ztt/python project/salience_detr/models/detectors/salience_detr.py", line 271, in forward
    loss_dict = self.criterion(output, targets)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self._call_impl(*args, **kwargs)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
File "/home/ubuntu/ztt/python project/salience_detr/models/bricks/set_criterion.py", line 152, in forward
    losses.update(self.calculate_loss(matching_outputs, targets, num_boxes))
File "/home/ubuntu/ztt/python project/salience_detr/models/bricks/set_criterion.py", line 126, in calculate_loss
    indices = list(map(self.matcher, pred_boxes, pred_logits, gt_boxes, gt_labels))
  File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
File "/home/ubuntu/ztt/python project/salience_detr/models/bricks/set_criterion.py", line 152, in forward
    losses.update(self.calculate_loss(matching_outputs, targets, num_boxes))
File "/home/ubuntu/ztt/python project/salience_detr/models/bricks/set_criterion.py", line 126, in calculate_loss
    indices = list(map(self.matcher, pred_boxes, pred_logits, gt_boxes, gt_labels))
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self._call_impl(*args, **kwargs)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
File "/home/ubuntu/ztt/python project/salience_detr/models/matcher/hungarian_matcher.py", line 80, in forward
    indices = linear_sum_assignment(c.cpu())
ValueError: matrix contains invalid numeric entries
    return forward_call(*args, **kwargs)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
File "/home/ubuntu/ztt/python project/salience_detr/models/matcher/hungarian_matcher.py", line 80, in forward
    indices = linear_sum_assignment(c.cpu())
ValueError: matrix contains invalid numeric entries
[2024-08-19 20:52:44,251] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 79816) of binary: /home/ubuntu/anaconda3/envs/salience_detr/bin/python
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/envs/salience_detr/bin/accelerate", line 8, in <module>
    sys.exit(main())
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1073, in launch_command
    multi_gpu_launcher(args)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/accelerate/commands/launch.py", line 718, in multi_gpu_launcher
    distrib_run.run(args)
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
File "/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-19_20:52:44
  host      : ubuntu-X640-G30
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 79817)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-19_20:52:44
  host      : ubuntu-X640-G30
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 79816)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### 环境信息

-------------------------------  -----------------------------------------------------------------------------------------
sys.platform                     linux
Python                           3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
numpy                            1.24.3
PyTorch                          2.2.2 @/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0,1                          NVIDIA GeForce RTX 4090 (arch=8.9)
Driver version                   535.183.01
CUDA_HOME                        /usr/local/cuda
Pillow                           10.2.0
torchvision                      0.17.2 @/home/ubuntu/anaconda3/envs/salience_detr/lib/python3.8/site-packages/torchvision
torchvision arch flags           5.0, 6.0, 7.0, 7.5, 8.0, 8.6, 9.0
fvcore                           0.1.5.post20221221
iopath                           0.1.10
cv2                              4.9.0
-------------------------------  -----------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

### 补充信息

作者你好，我想问一下这个报错是因为cost矩阵存在Nan值的问题吗？如果是这样，该从代码的哪里debug呢，有好的经验或者建议吗？
烦请拨冗回复指点一下，如果能指出代码的具体位置就更好了，谢谢！

后续我有调试了一下，发现双卡的断点不一样，但都在set_criterion.py中的 SetCriterion类中
有的是在计算num_boxes = torch.clamp(num_boxes / get_world_size(), min=1).item()报错
有的是在losses.update(self.calculate_loss(matching_outputs, targets, num_boxes))报错

**Comment by xiuqhou** [comment]
这个报错我遇到过很多次，并不是因为cost计算有问题，而是因为训练过程中其他部分出现了NaN，可能是数值溢出或者学习率太大。您可以尝试把学习率减小一点，关闭fp16或者bf16训练

**Comment by autoencoder-zz** [comment]
> 这个报错我遇到过很多次，并不是因为cost计算有问题，而是因为训练过程中其他部分出现了NaN，可能是数值溢出或者学习率太大。您可以尝试把学习率减小一点，关闭fp16或者bf16训练
训练是按照默认的条件，`--mixed_precision` was set to a value of `'no'`，没有开启fp16或者bf16训练
然后学习率从1e-4一直尝试调整到了1e-8，仍然报错。
我在encoder部分的self_att计算，也就是MultiScaleDeformableAttention函数中，attention weigths的计算进行了改动，在softmax之前加了一个变量权重。应该是这里的问题，那这样我该如何调试这个bug呢？

**Comment by autoencoder-zz** [comment]
> 这个报错我遇到过很多次，并不是因为cost计算有问题，而是因为训练过程中其他部分出现了NaN，可能是数值溢出或者学习率太大。您可以尝试把学习率减小一点，关闭fp16或者bf16训练

我在MultiScaleDeformableAttention函数中，在与权重变量加和之前打印attention weights发现，attention_weights张量中的值全是nan，感觉十分奇怪，这样与我对MultiScaleDeformableAttention函数的改动就没关系了

**Comment by xiuqhou** [comment]
我明白您的意思，你是说在你改动之前变量就已经出现了nan，所以应该不是你改动的问题。

但其实并不能这么分析，在报错的上一次反向传播就已经导致模型参数出现了nan，所以应该沿着反向传播的路径进行分析。当报错发生时，你可以从后往前逐层查看每层的parameter的grad，看从哪一层之前参数或者梯度全部变成了nan，就说明那一层的计算出现了问题，大概率是log、除法之类的没有限定范围或者出现了0/0.

下面举个简单的例子来说明为什么attention_weight之前就会出现nan，假设layer3出现了问题导致其前向传播正常，但反向传播后出现了nan。

```python
layer1->layer2->layer3->layer4->output（正常）
                                        \前向传播
                                        loss
                                        /反向传播
 nan  <- nan <- nan <- normal <- normal
```
这时候layer3前面层的参数经过反向传播后都为nan。这时候在进行下一次前向传播时，layer3之前的层和后面层的输出结果一直都是nan。

```python
输入-> layer1(nan) -> layer2(nan) -> layer3(nan) -> layer4(nan) -> output(nan) -> 报错
```

这就是为什么attention_weight之前会出现nan。所以您可以仔细检查下你改动的模块，有哪些操作可能导致nan。

**Comment by autoencoder-zz** [comment]
> 我明白您的意思，你是说在你改动之前变量就已经出现了nan，所以应该不是你改动的问题。
> 
> 但其实并不能这么分析，在报错的上一次反向传播就已经导致模型参数出现了nan，所以应该沿着反向传播的路径进行分析。当报错发生时，你可以从后往前逐层查看每层的parameter的grad，看从哪一层之前参数或者梯度全部变成了nan，就说明那一层的计算出现了问题，大概率是log、除法之类的没有限定范围或者出现了0/0.
> 
> 下面举个简单的例子来说明为什么attention_weight之前就会出现nan，假设layer3出现了问题导致其前向传播正常，但反向传播后出现了nan。
> 
> ```python
> layer1->layer2->layer3->layer4->output（正常）
>                                         \前向传播
>                                         loss
>                                         /反向传播
>  nan  <- nan <- nan <- normal <- normal
> ```
> 
> 这时候layer3前面层的参数经过反向传播后都为nan。这时候在进行下一次前向传播时，layer3之前的层和后面层的输出结果一直都是nan。
> 
> ```python
> 输入-> layer1(nan) -> layer2(nan) -> layer3(nan) -> layer4(nan) -> output(nan) -> 报错
> ```
> 
> 这就是为什么attention_weight之前会出现nan。所以您可以仔细检查下你改动的模块，有哪些操作可能导致nan。

我明白您的意思了，我改动的部分attention_weights = torch.log(torch.clamp(relative_weights, min=1e-6)) + attention_weights确实包括log运算，但是我防止-inf的出现，设置了最小值。

然后现在想按照你说的‘从后往前逐层查看每层的parameter的grad’对程序进行排查，查看parameter的grad，是要逐layer打印parameter吗？还是有更好的办法呢？

**Comment by xiuqhou** [comment]
可以重点关注一下您改动的前后几层，在报错的时候看下这几层的参数的grad是否为nan。

log(1e-6)虽然限制了输出不至于接近-inf，但梯度还是太大了，当fp16的时候就溢出了。哪怕没用fp16，梯度数值太大也容易导致训练不稳定：

![图片](https://github.com/user-attachments/assets/0a8ce597-9dfe-435c-b8b1-b0dd43708b0e)

不妨给log输入的参数`+1`，这样log输出的最小值从0开始，梯度会更稳定了。

```python
attention_weights = torch.log(torch.clamp(relative_weights, min=0) + 1) + attention_weights
```

PS: 我在Relation-DETR也遇到过log导致的数值问题，有一步是这样计算的：`delta_xy = torch.log(delta_xy / (wh1.unsqueeze(-2) + eps) + 1.0)`，如果不加后面的1.0就容易报错。

**Comment by autoencoder-zz** [comment]
> 可以重点关注一下您改动的前后几层，在报错的时候看下这几层的参数的grad是否为nan。
> 
> log(1e-6)虽然限制了输出不至于接近-inf，但梯度还是太大了，当fp16的时候就溢出了。哪怕没用fp16，梯度数值太大也容易导致训练不稳定：
> 
> ![图片](https://private-user-images.githubusercontent.com/49118282/359884402-0a8ce597-9dfe-435c-b8b1-b0dd43708b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjg5MTUsIm5iZiI6MTcyNDMyODYxNSwicGF0aCI6Ii80OTExODI4Mi8zNTk4ODQ0MDItMGE4Y2U1OTctOWRmZS00MzVjLWI4YjEtYjBkZDQzNzA4YjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEyMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMzMzM2Q4Y2Y5NjY3OGI2OTY3Y2FjYzQ2NDcxZjljNjNkNzM0ZDk5YTdhZjZmYjM3NWQ4MDljNGJhMjViZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bthLLLqQHnjSqHEmLk2AmzvHY2gVo1YOT5Loov84VPk)
> 
> 不妨给log输入的参数`+1`，这样log输出的最小值从0开始，梯度会更稳定了。
> 
> ```python
> attention_weights = torch.log(torch.clamp(relative_weights, min=0) + 1) + attention_weights
> ```
> 
> PS: 我在Relation-DETR也遇到过log导致的数值问题，有一步是这样计算的：`delta_xy = torch.log(delta_xy / (wh1.unsqueeze(-2) + eps) + 1.0)`，如果不加后面的1.0就容易报错。

感谢您细致的解答，学到了很多东西，我再多多尝试一下，谢谢。
